name: Deploy Astro site to Pages

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  id-token: write

jobs:
  deploy:
    uses: area44/workflow-hub/.github/workflows/astro.yml@v0.2.0
    with:
      run_deploy: true
